### ISSUE TITLE
Bower couldn't resolve spiritjs

### ISSUE THREAD

**Issue by ystreibel** [spirit/spirit#25]
Hi,

I need to use spiritjs in application that used bower and the github url is not available.
The github url is the old repository link https://github.com/inlet/spirit.js.git instead of https://github.com/spirit/spirit.git.

bower spiritjs#*            not-cached https://github.com/inlet/spirit.js.git#*
bower spiritjs#*               resolve https://github.com/inlet/spirit.js.git#*
bower spiritjs#*               ECMDERR Failed to execute "git ls-remote --tags --heads https://github.com/inlet/spirit.js.git", exit code of #128 remote: Repository not found. fatal: repository 'https://github.com/inlet/spirit.js.git/' not found

Additional error details:
remote: Repository not found.
fatal: repository 'https://github.com/inlet/spirit.js.git/' not found

Could you fix this ? 

PS: I couldn't migrate to another dependency tool manager now!

**Comment by inlet** [comment]
Hi @ystreibel,

I've dropped Bower support a while ago since everyone is moving away from it. Even the Bower team is recommending developers to move over to npm: 

https://medium.com/netscape/bye-bye-bower-or-how-to-migrate-from-bower-to-npm-and-webpack-4eb2e1121a50

If you're using a  bundler like Browserify, Webpack, Rollup etc, you can safely use the npm package or else use the global lib at `dist/spirit.min.js`.

See also: https://docs.spiritapp.io/gsap_runtime_include.html

I'm closing this issue now, please [drop me a mail](mailto:support@spiritapp.io) if you're encountering any issues. Thanks!
